# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from examples.filmology import schemas  # noqa: F401


class Movie(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    alias = schemas.StrSchema
                    color = schemas.StrSchema
                    country = schemas.StrSchema
                    URL = schemas.StrSchema
                    plot = schemas.StrSchema
                    runtime = schemas.StrSchema
                    date = schemas.DateSchema
                    
                    
                    class CompositionActor(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            items = schemas.StrSchema
                    
                        def __new__(
                            cls,
                            _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'CompositionActor':
                            return super().__new__(
                                cls,
                                _arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> MetaOapg.items:
                            return super().__getitem__(i)
                    
                    
                    class CompositionPosterPrimary(
                        schemas.StrBase,
                        schemas.NoneBase,
                        schemas.Schema,
                        schemas.NoneStrMixin
                    ):
                    
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[None, str, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'CompositionPosterPrimary':
                            return super().__new__(
                                cls,
                                *_args,
                                _configuration=_configuration,
                            )
                    
                    
                    class MovieAggregationDirector(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            items = schemas.StrSchema
                    
                        def __new__(
                            cls,
                            _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'MovieAggregationDirector':
                            return super().__new__(
                                cls,
                                _arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> MetaOapg.items:
                            return super().__getitem__(i)
                    
                    
                    class MovieAggregationPoster(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            items = schemas.StrSchema
                    
                        def __new__(
                            cls,
                            _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'MovieAggregationPoster':
                            return super().__new__(
                                cls,
                                _arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> MetaOapg.items:
                            return super().__getitem__(i)
                    __annotations__ = {
                        "alias": alias,
                        "color": color,
                        "country": country,
                        "URL": URL,
                        "plot": plot,
                        "runtime": runtime,
                        "date": date,
                        "CompositionActor": CompositionActor,
                        "CompositionPosterPrimary": CompositionPosterPrimary,
                        "MovieAggregationDirector": MovieAggregationDirector,
                        "MovieAggregationPoster": MovieAggregationPoster,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["alias"]) -> MetaOapg.properties.alias: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["country"]) -> MetaOapg.properties.country: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["URL"]) -> MetaOapg.properties.URL: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["plot"]) -> MetaOapg.properties.plot: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["runtime"]) -> MetaOapg.properties.runtime: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["date"]) -> MetaOapg.properties.date: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["CompositionActor"]) -> MetaOapg.properties.CompositionActor: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["CompositionPosterPrimary"]) -> MetaOapg.properties.CompositionPosterPrimary: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["MovieAggregationDirector"]) -> MetaOapg.properties.MovieAggregationDirector: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["MovieAggregationPoster"]) -> MetaOapg.properties.MovieAggregationPoster: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["alias", "color", "country", "URL", "plot", "runtime", "date", "CompositionActor", "CompositionPosterPrimary", "MovieAggregationDirector", "MovieAggregationPoster", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["alias"]) -> typing.Union[MetaOapg.properties.alias, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["color"]) -> typing.Union[MetaOapg.properties.color, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["country"]) -> typing.Union[MetaOapg.properties.country, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["URL"]) -> typing.Union[MetaOapg.properties.URL, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["plot"]) -> typing.Union[MetaOapg.properties.plot, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["runtime"]) -> typing.Union[MetaOapg.properties.runtime, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["date"]) -> typing.Union[MetaOapg.properties.date, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["CompositionActor"]) -> typing.Union[MetaOapg.properties.CompositionActor, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["CompositionPosterPrimary"]) -> typing.Union[MetaOapg.properties.CompositionPosterPrimary, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["MovieAggregationDirector"]) -> typing.Union[MetaOapg.properties.MovieAggregationDirector, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["MovieAggregationPoster"]) -> typing.Union[MetaOapg.properties.MovieAggregationPoster, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["alias", "color", "country", "URL", "plot", "runtime", "date", "CompositionActor", "CompositionPosterPrimary", "MovieAggregationDirector", "MovieAggregationPoster", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                alias: typing.Union[MetaOapg.properties.alias, str, schemas.Unset] = schemas.unset,
                color: typing.Union[MetaOapg.properties.color, str, schemas.Unset] = schemas.unset,
                country: typing.Union[MetaOapg.properties.country, str, schemas.Unset] = schemas.unset,
                URL: typing.Union[MetaOapg.properties.URL, str, schemas.Unset] = schemas.unset,
                plot: typing.Union[MetaOapg.properties.plot, str, schemas.Unset] = schemas.unset,
                runtime: typing.Union[MetaOapg.properties.runtime, str, schemas.Unset] = schemas.unset,
                date: typing.Union[MetaOapg.properties.date, str, date, schemas.Unset] = schemas.unset,
                CompositionActor: typing.Union[MetaOapg.properties.CompositionActor, list, tuple, schemas.Unset] = schemas.unset,
                CompositionPosterPrimary: typing.Union[MetaOapg.properties.CompositionPosterPrimary, None, str, schemas.Unset] = schemas.unset,
                MovieAggregationDirector: typing.Union[MetaOapg.properties.MovieAggregationDirector, list, tuple, schemas.Unset] = schemas.unset,
                MovieAggregationPoster: typing.Union[MetaOapg.properties.MovieAggregationPoster, list, tuple, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    alias=alias,
                    color=color,
                    country=country,
                    URL=URL,
                    plot=plot,
                    runtime=runtime,
                    date=date,
                    CompositionActor=CompositionActor,
                    CompositionPosterPrimary=CompositionPosterPrimary,
                    MovieAggregationDirector=MovieAggregationDirector,
                    MovieAggregationPoster=MovieAggregationPoster,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                EntityBaseExtended,
                cls.all_of_1,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Movie':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from examples.filmology.model.entity_base_extended import EntityBaseExtended
