# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from examples.filmology.paths.actor.post import CreateActor
from examples.filmology.paths.actor.delete import DeleteActor
from examples.filmology.paths.actor.get import ListActor
from examples.filmology.paths.actor.patch import PatchActor
from examples.filmology.paths.actor_id.get import RetreiveActor


class ActorApi(
    CreateActor,
    DeleteActor,
    ListActor,
    PatchActor,
    RetreiveActor,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
