# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from examples.filmology.paths.date.post import CreateDate
from examples.filmology.paths.date.delete import DeleteDate
from examples.filmology.paths.date.get import ListDate
from examples.filmology.paths.date.patch import PatchDate
from examples.filmology.paths.date_id.get import RetreiveDate


class DateApi(
    CreateDate,
    DeleteDate,
    ListDate,
    PatchDate,
    RetreiveDate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
