# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from examples.filmology.paths.director.post import CreateDirector
from examples.filmology.paths.director.delete import DeleteDirector
from examples.filmology.paths.director.get import ListDirector
from examples.filmology.paths.director.patch import PatchDirector
from examples.filmology.paths.director_id.get import RetreiveDirector


class DirectorApi(
    CreateDirector,
    DeleteDirector,
    ListDirector,
    PatchDirector,
    RetreiveDirector,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
