# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from examples.filmology.paths.genre.post import CreateGenre
from examples.filmology.paths.genre.delete import DeleteGenre
from examples.filmology.paths.genre.get import ListGenre
from examples.filmology.paths.genre.patch import PatchGenre
from examples.filmology.paths.genre_id.get import RetreiveGenre


class GenreApi(
    CreateGenre,
    DeleteGenre,
    ListGenre,
    PatchGenre,
    RetreiveGenre,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
