# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from examples.filmology.paths.language.post import CreateLanguage
from examples.filmology.paths.language.delete import DeleteLanguage
from examples.filmology.paths.language.get import ListLanguage
from examples.filmology.paths.language.patch import PatchLanguage
from examples.filmology.paths.language_id.get import RetreiveLanguage


class LanguageApi(
    CreateLanguage,
    DeleteLanguage,
    ListLanguage,
    PatchLanguage,
    RetreiveLanguage,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
