# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from examples.filmology.paths.movie.post import CreateMovie
from examples.filmology.paths.movie.delete import DeleteMovie
from examples.filmology.paths.movie.get import ListMovie
from examples.filmology.paths.movie.patch import PatchMovie
from examples.filmology.paths.movie_id.get import RetreiveMovie


class MovieApi(
    CreateMovie,
    DeleteMovie,
    ListMovie,
    PatchMovie,
    RetreiveMovie,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
