# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

from examples.filmology.paths.poster.post import CreatePoster
from examples.filmology.paths.poster.delete import DeletePoster
from examples.filmology.paths.poster.get import ListPoster
from examples.filmology.paths.poster.patch import PatchPoster
from examples.filmology.paths.poster_id.get import RetreivePoster


class PosterApi(
    CreatePoster,
    DeletePoster,
    ListPoster,
    PatchPoster,
    RetreivePoster,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
