# coding: utf-8

# flake8: noqa

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from examples.filmology.api_client import ApiClient

# import Configuration
from examples.filmology.configuration import Configuration

# import exceptions
from examples.filmology.exceptions import OpenApiException
from examples.filmology.exceptions import ApiAttributeError
from examples.filmology.exceptions import ApiTypeError
from examples.filmology.exceptions import ApiValueError
from examples.filmology.exceptions import ApiKeyError
from examples.filmology.exceptions import ApiException
