# coding: utf-8

"""
    FilmologyManagement

    Filmology is a test API that describes all the possible variant of a DAF + API model and his implementation as a DigitalPy application  # noqa: E501

    The version of the OpenAPI document: 24.11.26
    Contact: Freetakteam@gmail.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import examples.filmology
from examples.filmology.model.entity_base_extended import EntityBaseExtended
from examples.filmology import configuration


class TestEntityBaseExtended(unittest.TestCase):
    """EntityBaseExtended unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
